name: 'PHP Unit Test SelfRunner'
description: 'PHP Unit Test SelfRunner'

inputs:
  config-file:
    description: 'Path to phpunit.xml'
    required: true
    default: phpunit.xml.dist

  additional-parameters:
    description: 'Additional parameters for the phpunit command'
    required: true
    default: ''

  public-project:
    description: 'Public or Provate project'
    required: true
    default: 'no'

  app-local-php:
    description: 'App Local PHP Config'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup config
      if: ${{ inputs.public-project == 'no' }}
      run: mv ./config/app_local_ci.php ./config/app_local.php
      shell: bash

    - name: Setup secret config
      if: ${{ inputs.public-project == 'yes' }}
      run: echo "${{ inputs.app-local-php }}" > ./config/app_local.php
      shell: bash

    - name: Setup ca.pem
      run: cp /home/actions-runner/CA.pem ./config/CA.pem
      shell: bash

    - name: Copy composer.phar
      run: cp /home/actions-runner/composer.phar composer.phar
      shell: bash

    - name: Composer install
      run: ./composer.phar install
      shell: bash

    - name: UnitTest
      run: vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer --colors=always --configuration ${{ inputs.config-file }} ${{ inputs.additional-parameters }}
      shell: bash