name: 'PHP Unit Test SelfRunner'
description: 'PHP Unit Test SelfRunner'

inputs:
  config-file:
    description: 'Path to phpunit.xml'
    required: true
    default: phpunit.xml.dist

  additional-parameters:
    description: 'Additional parameters for the phpunit command'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set Variables
      run: |
          if [[ $GITHUB_REPOSITORY == *"eggheads-ozon"* ]]; then
              echo "WORK_DIR=$HOME/runner_ozon/configs" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REPOSITORY == *"php-eggheads"* ]]; then
              echo "WORK_DIR=$HOME/runner_eggheads/configs" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REPOSITORY == *"php-eggheads"* ]]; then
              echo "WORK_DIR=$HOME/runner_eggheads/configs" >> "$GITHUB_ENV"
          fi

    - name: Setup config
      run: cp $WORK_DIR/app_local.php ./config/app_local.php      
      shell: bash

    - name: Setup ca.pem
      run: cp ~/CA.pem ./config/CA.pem
      shell: bash

    - name: Copy composer.phar
      run: cp ~/composer.phar composer.phar
      shell: bash

    - name: Create tmp folder
      run: mkdir -p ./tmp
      shell: bash

    - name: Copy php-backend-token
      if: ${{ contains(github.repository, 'eggheads-ozon') || ${{ contains(github.repository, 'php-eggheads') }}
      run: cp $WORK_DIR/php-backend-token.json ./tmp/php-backend.json
      shell: bash

    - name: Copy php-frontend.json
      if: ${{ contains(github.repository, 'php-eggheads') }}
      run: cp $WORK_DIR/php-frontend.json ./config/php-frontend.json
      shell: bash

    - name: Copy php-backend-token.json
      if: ${{ contains(github.repository, 'php-eggheads') }}
      run: cp $WORK_DIR/php-backend-token.json ./tmp/php-backend.json
      shell: bash

    - name: Copy wb_supplier_token.conf
      if: ${{ contains(github.repository, 'php-eggheads') }}
      run: cp $WORK_DIR/wb_supplier_token.conf ./tmp/wb_supplier_token.conf
      shell: bash

    - name: Composer install
      run: ~/composer.phar install
      shell: bash

    - name: MySQL run init.sql
      if: ${{ contains(github.repository, 'eggheads-ozon') || ${{ contains(github.repository, 'php-eggheads') }}
      run: cat $WORK_DIR/eggheads-init.sql | mysql --login-path=php-eggheads.conf
      shell: bash

    - name: MySQL run eggheads.sql
      if: ${{ contains(github.repository, 'php-eggheads') }}
      run: cat $WORK_DIR/eggheads.sql | mysql --login-path=php-eggheads.conf -Deggheads_release
      shell: bash

    - name: Run migrations
      if: ${{ contains(github.repository, 'eggheads-ozon') || ${{ contains(github.repository, 'php-eggheads') }}
      run: vendor/bin/phinx migrate
      shell: bash

    - name: UnitTest
      run: vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer --colors=always --configuration ${{ inputs.config-file }} ${{ inputs.additional-parameters }}
      shell: bash

    - name: Refresh Supplier Cabinet token
      if: ${{ contains(github.repository, 'php-eggheads') }}
      run: cp -p ./tmp/wb_supplier_token.conf $WORK_DIR/wb_supplier_token.conf
      shell: bash